name: ser2net server
version: 0.0.2
slug: ser2net
description: 'Expose serial ports over the network, including RFC2217 support for
  remote port settings change (e.g. baud rate or RTS)

  '
url: https://github.com/jhollowe/addon-ser2net
codenotary: codenotary@johnhollowell.com
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
ports:
  12345/tcp: 7000
  12346/tcp: 7001
ports_description:
  12345/tcp: port to access serial device (tcp or telnet/rfc2217)
  12346/tcp: port to access admin interface (if enabled))
uart: true
options:
  serial_device: /dev/ttyACM0
  max_connections: 1
  enable_admin_interface: true
schema:
  serial_device: device(subsystem=tty)
  max_connections: int
  enable_admin_interface: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/jhollowe-addons/ser2net-{arch}
